---
- hosts: hardened
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - { role: prepare, tags: prepare }
    - { role: kernel, tags: kernel }
    - { role: fs, tags: fs }
    - { role: permissions, tags: permissions }
    - { role: firewall, tags: firewall }
    # - { role: apparmor, tags: apparmor }
    # - { role: sshd, tags: sshd }
    # - { role: apt, tags: apt }
    # - { role: ids, tags: ids }
    # - { role: clamav, tags: clamav }
    # - { role: auditd, tags: auditd }
    # - { role: rkhunter, tags: rkhunter }