- name: Update all packages
  apt:
      update_cache: yes
      upgrade: dist

- name: Remove apport
  apt:
      name: apport
      state: absent

- name: Remove snapd
  apt:
    name: snapd
    state: absent

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Check if a reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc == 0

- name: Reboot box if kernel/libs updated and requested by the system
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel is needed'
  args:
      removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
  when: reboot_required.rc == 0

- name: Wait for system to become reachable again
  wait_for_connection:
      delay: 60
      timeout: 300
  when: reboot_required.rc == 0